version: '3.8'

services:
  webcrawlerapi:
    build:
      context: ./WebCrawlerAPI  # context should point to the folder containing the Dockerfile
      dockerfile: Dockerfile    # Dockerfile is in the context folder
    volumes:
      - ./WebCrawlerAPI/WebCrawler.db:/app/WebCrawler.db  # Mount the correct path
    ports:
      - "8080:80"
