name: .NET Build

on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [8.0.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test WebCrawlerTests/WebCrawlerTests.csproj --no-restore --verbosity normal
